#!/usr/bin/python
#
# Copyright 2004 Matt Mackall <mpm@selenic.com>
#
# inspired by perl Bloat-O-Meter (c) 1997 by Andi Kleen
#
# This software may be used and distributed according to the terms
# of the GNU General Public License, incorporated herein by reference.

import sys, os, re, getopt

do_sections = do_functions = False

options, remainder = getopt.gnu_getopt(sys.argv[1:], 'sf', [ 'sections', 'functions' ])
if len(remainder) != 2:
    sys.stderr.write("usage: %s [-f|--functions] [-s|--sections] file1 file2\n" % sys.argv[0])
    sys.exit(-1)

for opt, arg in options:
    if opt in ('-s', '--sections'):
        do_sections = True
    if opt in ('-f', '--functions'):
        do_functions = True

if not options:
    do_functions = True

def getsizes(file):
    sym = {}
    for l in os.popen("nm --size-sort " + file).readlines():
        size, type, name = l[:-1].split()
        if type in "tTdDbBrR":
            # strip generated symbols
            if name.startswith("__mod_"): continue
            if name.startswith("SyS_"): continue
            if name.startswith("compat_SyS_"): continue
            if name == "linux_banner": continue
            # statics and some other optimizations adds random .NUMBER
            name = re.sub(r'\.[0-9]+', '', name)
            sym[name] = sym.get(name, 0) + int(size, 16)
    return sym

def getsections(file):
    sym = {}
    for l in os.popen("objdump -h -w " + file).readlines():
        line_tokens = l.split()
        # retain Size column index
        if "Size" in l:
            idx = line_tokens.index("Size")
        # cumulate all section's sizes
        for section in ".rodata", ".text", ".debug":
            if section in l:
                if section not in sym:
                    sym[section] = 0
                sym[section] += int(line_tokens[idx], 16)
    return sym

def print_delta(type, old, new):
    grow, shrink, add, remove, up, down = 0, 0, 0, 0, 0, 0
    delta, common = [], {}
    otot, ntot = 0, 0

    for a in old:
        if a in new:
            common[a] = 1

    for name in old:
        otot += old[name]
        if name not in common:
            remove += 1
            down += old[name]
            delta.append((-old[name], name))

    for name in new:
        ntot += new[name]
        if name not in common:
            add += 1
            up += new[name]
            delta.append((new[name], name))

    for name in common:
            d = new.get(name, 0) - old.get(name, 0)
            if d>0: grow, up = grow+1, up+d
            if d<0: shrink, down = shrink+1, down-d
            delta.append((d, name))

    delta.sort()
    delta.reverse()

    print("add/remove: %s/%s grow/shrink: %s/%s up/down: %s/%s (%s)" % \
          (add, remove, grow, shrink, up, -down, up-down))
    print("%-40s %7s %7s %+7s" % (type, "old", "new", "delta"))
    for d, n in delta:
        if d: print("%-40s %7s %7s %+7d" % (n, old.get(n,"-"), new.get(n,"-"), d))

    print("Total: Before=%d, After=%d, chg %f%%" % \
        (otot, ntot, (ntot - otot) * 100.0 / otot))

    return

print("bloat-o-meter comparison of %s and %s" % (remainder[0], remainder[1]))

if do_functions:
    old = getsizes(remainder[0])
    new = getsizes(remainder[1])
    print_delta("function", old, new)

if do_sections:
    old = getsections(remainder[0])
    new = getsections(remainder[1])
    print_delta("section", old, new)
